### ISSUE TITLE
Issue with Buckets

### ISSUE THREAD

**Issue by Bob-web-eng** [KBD2/terrario#3]
When I fill and then empty a water bucket, I suddenly have 11 empty buckets instead of 1. This issue only appears to happen when emptying the  buckets after they have been filled with water.
I posted this just to let you know.

**Comment by KBD2** [comment]
I can't reproduce this on the latest release or latest commit, are you sure it's not just stacking with other buckets in your inventory?

**Comment by Bob-web-eng** [comment]
Sorry for not replying, however the latest release seems to fix the problem.
thanks
